# render.yaml
# Corrigido para remover o 'npm install' do preDeployCommand

services:
  # ----------------- Backend (Nest.js com Prisma) -----------------
  - type: web
    name: cinema-backend
    env: docker
    dockerContext: ./cinema-backend
    dockerfilePath: ./cinema-backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: cinema-db
          property: connectionString

    # --- CORREÇÃO AQUI ---
    # Removido o "npm install &&". O preDeployCommand deve apenas rodar a migração.
    preDeployCommand: "npx prisma migrate deploy"
    
    startCommand: "node dist/src/main.js"

  # ----------------- Frontend (React com Nginx) -----------------
  - type: web
    name: cinema-frontend
    # ... (o resto da configuração do frontend permanece igual) ...
    env: docker
    dockerContext: ./cinema-frontend
    dockerfilePath: ./cinema-frontend/Dockerfile
    plan: free
    build:
      args:
        NEXT_PUBLIC_API_URL: "/api"

    rewrites:
      - source: /api/:path*
        destination: https://cinema-backend.onrender.com/:path*

# Seção SEPARADA e de nível superior para bancos de dados
databases:
  - name: cinema-db
    plan: free
    databaseName: cinema
    user: admin