# render.yaml
# Versão com a estrutura correta: 'services' e 'databases' são seções separadas.

# Seção para serviços web, workers em segundo plano, etc.
services:
  # ----------------- Backend (Nest.js com Prisma) -----------------
  - type: web
    name: cinema-backend
    env: docker
    dockerContext: ./cinema-backend
    dockerfilePath: ./cinema-backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          # O nome aqui deve corresponder ao nome do banco na seção 'databases'
          name: cinema-db
          property: connectionString

    preDeployCommand: "npm install && npx prisma migrate deploy"
    startCommand: "node dist/src/main.js"

  # ----------------- Frontend (React com Nginx) -----------------
  - type: web
    name: cinema-frontend
    env: docker
    dockerContext: ./cinema-frontend
    dockerfilePath: ./cinema-frontend/Dockerfile
    plan: free
    build:
      args:
        NEXT_PUBLIC_API_URL: "/api"

    rewrites:
      - source: /api/:path*
        destination: https://cinema-backend.onrender.com/:path*

# Seção SEPARADA e de nível superior para bancos de dados
databases:
  # A lista de bancos de dados não usa a propriedade 'type'
  - name: cinema-db # Nome de referência para o serviço
    plan: free
    databaseName: cinema # Nome do banco de dados (igual ao seu docker-compose)
    user: admin          # Nome do usuário (igual ao seu docker-compose)