services:
  - type: web
    name: cinema-backend
    env: docker
    dockerContext: ./cinema-backend
    dockerfilePath: ./cinema-backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: cinema-db
          property: connectionString
    preDeployCommand: "npx prisma migrate deploy"
    startCommand: "node dist/src/main.js"
  - type: web
    name: cinema-frontend
    env: docker
    dockerContext: ./cinema-frontend
    dockerfilePath: ./cinema-frontend/Dockerfile
    plan: free
    build:
      args:
        NEXT_PUBLIC_API_URL: "/api"
    rewrites:
      - source: /api/:path*
        destination: https://cinema-backend.onrender.com/:path*
databases:
  - name: cinema-db
    plan: free
    databaseName: cinema
    user: admin