services:
  - type: web
    name: cinema-backend
    env: docker
    plan: free
    dockerContext: cinema-backend
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: cinema-db
          property: connectionString

  - type: web
    name: cinema-frontend
    env: docker
    plan: free
    dockerContext: cinema-frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://cinema-backend-3ej3.onrender.com/api" # <- Use a URL completa, não apenas "/api"

databases:
  - name: cinema-db
    plan: free
    databaseName: cinema
    user: admin
